import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="min-h-screen">
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto px-4 py-8">
        <h1 className="text-4xl font-bold mb-4">
          Welcome to My App
        </h1>
        <p className="text-xl">
          Get started by editing{' '}
          <code className="bg-gray-100 p-1 rounded">pages/index.tsx</code>
        </p>
      </main>
    </div>
  )
}

export default Home 